import React from "react";
import { COLORS } from "./theme";

let Proyectos = [
    {
        id:0, 
        nombre: "Terraza Abel", 
        categoria:"1",
        color:COLORS.A,
        icono:"deck",
        tickets: [
            {
                TicketId:0.1,
                nombre:"Materiales para piso de baño principal",
                solicitante:"Leandro Diaz Meiners",
                numero:1,
                plazo:15,
                estado:1,
                prioridad:1,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:0.2,
                nombre:"Nombre 2",
                solicitante:"Solicitante 1",
                numero:2,
                plazo:1,
                estado:2,
                prioridad:2,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:0.3,
                nombre:"Nombre 3",
                solicitante:"Solicitante 1",
                numero:3,
                plazo:1,
                estado:3,
                prioridad:3,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
        ],
    },
    {
        id:1, 
        nombre: "Pileta Leandro Diaz Meiners", 
        categoria:"2",
        color:COLORS.B,
        icono:"pool",
        tickets: [
            {
                TicketId:1.1,
                nombre:"Nombre 1",
                solicitante:"Solicitante 2",
                numero:4,
                plazo:1,
                estado:1,
                prioridad:1,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:1.2,
                nombre:"Nombre 2",
                solicitante:"Solicitante 2",
                numero:5,
                plazo:1,
                estado:2,
                prioridad:2,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:1.3,
                nombre:"Nombre 3",
                solicitante:"Solicitante 2",
                numero:6,
                plazo:1,
                estado:3,
                prioridad:3,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
        ], 
    },
    {
        id:2, 
        nombre: "Casa Cecilia", 
        categoria:"3",
        color:COLORS.C,
        icono:"house",
        tickets: [
            {
                TicketId:2.1,
                nombre:"Nombre 1",
                solicitante:"Solicitante 3",
                numero:7,
                plazo:1,
                estado:1,
                prioridad:1,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:2.2,
                nombre:"Nombre 2",
                solicitante:"Solicitante 3",
                numero:8,
                plazo:1,
                estado:2,
                prioridad:2,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:2.3,
                nombre:"Nombre 3",
                solicitante:"Solicitante 3",
                numero:9,
                plazo:1,
                estado:3,
                prioridad:3,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
        ], 
    },
    {
        id:3, 
        nombre: "Proyecto 4", 
        categoria:"4",
        color:COLORS.D,
        icono:"countertops",
        tickets: [
            {
                TicketId:3.1,
                nombre:"Nombre 1",
                solicitante:"Solicitante 4",
                numero:10,
                plazo:1,
                estado:1,
                prioridad:1,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:3.2,
                nombre:"Nombre 2",
                solicitante:"Solicitante 4",
                numero:11,
                plazo:1,
                estado:2,
                prioridad:2,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:3.3,
                nombre:"Nombre 3",
                solicitante:"Solicitante 4",
                numero:12,
                plazo:1,
                estado:3,
                prioridad:3,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
        ],
    },
    {
        id:4, 
        nombre: "Proyecto 5", 
        categoria:"5",
        color:COLORS.E,
        icono:"apartment",
        tickets: [
            {
                TicketId:4.1,
                nombre:"Nombre 1",
                solicitante:"Solicitante 5",
                numero:13,
                plazo:1,
                estado:1,
                prioridad:1,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:4.2,
                nombre:"Nombre 2",
                solicitante:"Solicitante 5",
                numero:14,
                plazo:1,
                estado:2,
                prioridad:2,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:4.3,
                nombre:"Nombre 3",
                solicitante:"Solicitante 5",
                numero:15,
                plazo:1,
                estado:3,
                prioridad:3,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
        ],
    },
    {
        id:5, 
        nombre: "Proyecto 6", 
        categoria:"6",
        color:COLORS.F,
        icono:"store",
        tickets: [
            {
                TicketId:5.1,
                nombre:"Nombre 1",
                solicitante:"Solicitante 6",
                numero:16,
                plazo:1,
                estado:1,
                prioridad:1,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:5.2,
                nombre:"Nombre 2",
                solicitante:"Solicitante 6",
                numero:17,
                plazo:1,
                estado:2,
                prioridad:2,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:5.3,
                nombre:"Nombre 3",
                solicitante:"Solicitante 6",
                numero:18,
                plazo:1,
                estado:3,
                prioridad:3,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
        ],
    },
    {
        id:6, 
        nombre: "Proyecto 7", 
        categoria:"7",
        color:COLORS.G,
        icono:"restaurant",
        tickets: [
            {
                TicketId:6.1,
                nombre:"Nombre 1",
                solicitante:"Solicitante 7",
                numero:19,
                plazo:1,
                estado:1,
                prioridad:1,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:6.2,
                nombre:"Nombre 2",
                solicitante:"Solicitante 7",
                numero:20,
                plazo:1,
                estado:2,
                prioridad:2,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
            {
                TicketId:6.3,
                nombre:"Nombre 3",
                solicitante:"Solicitante 7",
                numero:21,
                plazo:1,
                estado:3,
                prioridad:3,
                materiales: [
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:1,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                    {
                        MatsId:2,
                        nombre: "Pastina Impermeable Antihongos Alta Performance",
                        marca:"Klaukol",
                        presentacion: "Siena",
                        unidad: "Bolsa 1 Kg.",
                        cantidad:10,
                    },
                ],
            },
        ],
    },
]

export default Proyectos;